# Abstract 

It is often very difficult to make accurate projections about how interventions will affect the real world and to use such projections to develop effective implementation plans, monitor progress and evaluate project impacts. This is due to a variety of factors including lack of data, complex impact pathways, and risks and uncertainties that are difficult to factor into intervention planning. Scientific approaches to produce reliable impact projections are rarely applied in agricultural development, but Decision Analysis techniques commonly used in other fields have the potential to improve development decisions. This manual outlines a Decision Analysis approach that can help decision-makers efficiently allocate resources for the most effective policy impacts. 

The procedures outlined in this manual feature the construction of causal models – models that describe the mechanisms through which intervention impacts will be delivered – that are co-developed by experts, stakeholders and analysts through facilitated participatory processes. These models are then formalized as Bayesian Network (BN) models, a modeling approach that has been widely applied in a range of disciplines, including medical sciences, genetics, environmental sciences, and legal reasoning. BNs allow for the formal representation of causal models, such as intervention impact pathways. They can work effectively with incomplete information, combine expert knowledge with other sources of information, and they allow adequate consideration of risk.

This manual illustrates the use of participatory workshops that convene experts on the systems, stakeholders involved in ongoing or prospective projects, and analysts. These teams can jointly develop impact pathways for the interventions, which can be formalized into quantitative BN models. After several rounds of feedback elicitation, and inclusion of data from experts and other sources, stochastic simulations can be run to determine the likely impacts of the interventions. Results can be presented back to stakeholders for feedback. 

Through the tools laid out in this manual critical uncertainties in the models of intervention impact pathways can be identified. These high-value variables can determine uncertainty about project outcomes. Further measurement or dissagregation of these variables could greatly support decision-making processes. 

By demonstrating improved intervention decisions with little additional investment and improved tools for intervention decision modeling, we hope that this approach will be widely adopted and used to enhance the efficacy of development activities.

